import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "EU individuals using social networks",
  "subtitle": "Across the EU, around 73% of share of individuals used the internet for social networks. Ranging from 56.4% in Italy to 89.7% in Denmark, with Cyprus, Malta, Finland and the Netherlands also among the highest-ranking countries.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nBelgium,BE,0.6768,false,67.68% according to the selected indicator.,,,,,,,,\nBulgaria,BG,0.7106,false,71.06% according to the selected indicator.,,,,,,,,\nCzechia,CZ,0.7009,false,70.09% according to the selected indicator.,,,,,,,,\nDenmark,DK,0.8966,false,89.66% according to the selected indicator.,,,,,,,,\nGermany,DE,0.5924,false,59.24% according to the selected indicator.,,,,,,,,\nEstonia,EE,0.7258,false,72.58% according to the selected indicator.,,,,,,,,\nIreland,IE,0.7989,false,79.89% according to the selected indicator.,,,,,,,,\nGreece,EL,0.7304,false,73.04% according to the selected indicator.,,,,,,,,\nSpain,ES,0.6950,false,69.50% according to the selected indicator.,,,,,,,,\nFrance,FR,0.7075,false,70.75% according to the selected indicator.,,,,,,,,\nCroatia,HR,0.6150,false,61.50% according to the selected indicator.,,,,,,,,\nItaly,IT,0.5638,false,56.38% according to the selected indicator.,,,,,,,,\nCyprus,CY,0.8654,false,86.54% according to the selected indicator.,,,,,,,,\nLatvia,LV,0.7929,false,79.29% according to the selected indicator.,,,,,,,,\nLithuania,LT,0.7027,false,70.27% according to the selected indicator.,,,,,,,,\nLuxembourg,LU,0.6732,false,67.32% according to the selected indicator.,,,,,,,,\nHungary,HU,0.7866,false,78.66% according to the selected indicator.,,,,,,,,\nMalta,MT,0.8242,false,82.42% according to the selected indicator.,,,,,,,,\nNetherlands,NL,0.8121,false,81.21% according to the selected indicator.,,,,,,,,\nAustria,AT,0.6786,false,67.86% according to the selected indicator.,,,,,,,,\nPoland,PL,0.6327,false,63.27% according to the selected indicator.,,,,,,,,\nPortugal,PT,0.7046,false,70.46% according to the selected indicator.,,,,,,,,\nRomania,RO,0.7957,false,79.57% according to the selected indicator.,,,,,,,,\nSlovenia,SI,0.6543,false,65.43% according to the selected indicator.,,,,,,,,\nSlovakia,SK,0.6191,false,61.91% according to the selected indicator.,,,,,,,,\nFinland,FI,0.8132,false,81.32% according to the selected indicator.,,,,,,,,\nSweden,SE,0.7472,false,74.72% according to the selected indicator.,,,,,,,,",
  "parsedData": [
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.6768,
      "extraInfo": false,
      "text_content": "67.68% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.7106,
      "extraInfo": false,
      "text_content": "71.06% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.7009,
      "extraInfo": false,
      "text_content": "70.09% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.8966,
      "extraInfo": false,
      "text_content": "89.66% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.5924,
      "extraInfo": false,
      "text_content": "59.24% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.7258,
      "extraInfo": false,
      "text_content": "72.58% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.7989,
      "extraInfo": false,
      "text_content": "79.89% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.7304,
      "extraInfo": false,
      "text_content": "73.04% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.695,
      "extraInfo": false,
      "text_content": "69.50% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.7075,
      "extraInfo": false,
      "text_content": "70.75% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.615,
      "extraInfo": false,
      "text_content": "61.50% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.5638,
      "extraInfo": false,
      "text_content": "56.38% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.8654,
      "extraInfo": false,
      "text_content": "86.54% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.7929,
      "extraInfo": false,
      "text_content": "79.29% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.7027,
      "extraInfo": false,
      "text_content": "70.27% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.6732,
      "extraInfo": false,
      "text_content": "67.32% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.7866,
      "extraInfo": false,
      "text_content": "78.66% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.8242,
      "extraInfo": false,
      "text_content": "82.42% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.8121,
      "extraInfo": false,
      "text_content": "81.21% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.6786,
      "extraInfo": false,
      "text_content": "67.86% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.6327,
      "extraInfo": false,
      "text_content": "63.27% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.7046,
      "extraInfo": false,
      "text_content": "70.46% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.7957,
      "extraInfo": false,
      "text_content": "79.57% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.6543,
      "extraInfo": false,
      "text_content": "65.43% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.6191,
      "extraInfo": false,
      "text_content": "61.91% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.8132,
      "extraInfo": false,
      "text_content": "81.32% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.7472,
      "extraInfo": false,
      "text_content": "74.72% according to the selected indicator.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "orange-red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Following cases are visualized with this data: participating in social networks (creating user profile, posting messages or other contributions to facebook, twitter, etc.). No data available for France.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/tin00127/default/table?lang=en",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "EU individuals using social networks",
    "subtitle": "Across the EU, around 73% of share of individuals used the internet for social networks. Ranging from 56.4% in Italy to 89.7% in Denmark, with Cyprus, Malta, Finland and the Netherlands also among the highest-ranking countries.",
    "textNoteDescription": "Note",
    "textNote": "Following cases are visualized with this data: participating in social networks (creating user profile, posting messages or other contributions to facebook, twitter, etc.). No data available for France.",
    "textSourceDescription": "Source",
    "textSource": "Eurostat (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_BE": "67.68% according to the selected indicator.",
    "extraInfo_BG": "71.06% according to the selected indicator.",
    "extraInfo_CZ": "70.09% according to the selected indicator.",
    "extraInfo_DK": "89.66% according to the selected indicator.",
    "extraInfo_DE": "59.24% according to the selected indicator.",
    "extraInfo_EE": "72.58% according to the selected indicator.",
    "extraInfo_IE": "79.89% according to the selected indicator.",
    "extraInfo_EL": "73.04% according to the selected indicator.",
    "extraInfo_ES": "69.50% according to the selected indicator.",
    "extraInfo_FR": "70.75% according to the selected indicator.",
    "extraInfo_HR": "61.50% according to the selected indicator.",
    "extraInfo_IT": "56.38% according to the selected indicator.",
    "extraInfo_CY": "86.54% according to the selected indicator.",
    "extraInfo_LV": "79.29% according to the selected indicator.",
    "extraInfo_LT": "70.27% according to the selected indicator.",
    "extraInfo_LU": "67.32% according to the selected indicator.",
    "extraInfo_HU": "78.66% according to the selected indicator.",
    "extraInfo_MT": "82.42% according to the selected indicator.",
    "extraInfo_NL": "81.21% according to the selected indicator.",
    "extraInfo_AT": "67.86% according to the selected indicator.",
    "extraInfo_PL": "63.27% according to the selected indicator.",
    "extraInfo_PT": "70.46% according to the selected indicator.",
    "extraInfo_RO": "79.57% according to the selected indicator.",
    "extraInfo_SI": "65.43% according to the selected indicator.",
    "extraInfo_SK": "61.91% according to the selected indicator.",
    "extraInfo_FI": "81.32% according to the selected indicator.",
    "extraInfo_SE": "74.72% according to the selected indicator."
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_BE": "67.68% according to the selected indicator.",
  "extraInfo_BG": "71.06% according to the selected indicator.",
  "extraInfo_CZ": "70.09% according to the selected indicator.",
  "extraInfo_DK": "89.66% according to the selected indicator.",
  "extraInfo_DE": "59.24% according to the selected indicator.",
  "extraInfo_EE": "72.58% according to the selected indicator.",
  "extraInfo_IE": "79.89% according to the selected indicator.",
  "extraInfo_EL": "73.04% according to the selected indicator.",
  "extraInfo_ES": "69.50% according to the selected indicator.",
  "extraInfo_FR": "70.75% according to the selected indicator.",
  "extraInfo_HR": "61.50% according to the selected indicator.",
  "extraInfo_IT": "56.38% according to the selected indicator.",
  "extraInfo_CY": "86.54% according to the selected indicator.",
  "extraInfo_LV": "79.29% according to the selected indicator.",
  "extraInfo_LT": "70.27% according to the selected indicator.",
  "extraInfo_LU": "67.32% according to the selected indicator.",
  "extraInfo_HU": "78.66% according to the selected indicator.",
  "extraInfo_MT": "82.42% according to the selected indicator.",
  "extraInfo_NL": "81.21% according to the selected indicator.",
  "extraInfo_AT": "67.86% according to the selected indicator.",
  "extraInfo_PL": "63.27% according to the selected indicator.",
  "extraInfo_PT": "70.46% according to the selected indicator.",
  "extraInfo_RO": "79.57% according to the selected indicator.",
  "extraInfo_SI": "65.43% according to the selected indicator.",
  "extraInfo_SK": "61.91% according to the selected indicator.",
  "extraInfo_FI": "81.32% according to the selected indicator.",
  "extraInfo_SE": "74.72% according to the selected indicator."
});